import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI, Type } from '@google/genai';

const apiKey = process.env.GEMINI_API_KEY || '';

// ─── Schema ───────────────────────────────────────────────────────────────────
const ANALYSIS_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    steps: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          category: { type: Type.STRING },
          question: { type: Type.STRING },
          suggestions: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: 'Exactly 4 quick reply options.',
          },
        },
        required: ['category', 'question', 'suggestions'],
      },
    },
    guidance: {
      type: Type.OBJECT,
      properties: {
        tips: { type: Type.ARRAY, items: { type: Type.STRING } },
        potentialConditions: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              explanation: { type: Type.STRING },
            },
            required: ['name', 'explanation'],
          },
        },
        urgency: { type: Type.STRING, enum: ['Green', 'Yellow', 'Red'] },
      },
      required: ['tips', 'potentialConditions', 'urgency'],
    },
    clinicalReport: {
      type: Type.OBJECT,
      properties: {
        narrative: { type: Type.STRING },
        summaryTable: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              label: { type: Type.STRING },
              value: { type: Type.STRING },
            },
            required: ['label', 'value'],
          },
        },
        doctorQuestions: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: ['narrative', 'summaryTable', 'doctorQuestions'],
    },
  },
  required: ['steps', 'guidance', 'clinicalReport'],
};

// ─── Language helpers ─────────────────────────────────────────────────────────
const OUTPUT_LANG_NAMES: Record<string, string> = {
  EN: 'English',
  AR: 'Arabic',
  HI: 'Hindi',
  UR: 'Urdu',
};

function buildPrompt(userData: any, uiLang: string, outputLang: string): string {
  const outputLangName = OUTPUT_LANG_NAMES[outputLang] || 'English';
  const interviewLangName = OUTPUT_LANG_NAMES[uiLang] || 'English';

  return `
ROLE: Clara — Clinical Triage Expert.
MISSION: Transform patient symptoms into a respectful 2-frame clinical report.

LANGUAGE DIRECTIVE:
- Interview questions (steps): ${interviewLangName}.
- Final clinical report (guidance + clinicalReport): ${outputLangName}.
- Accept any dialect or informal language as input — understand it fully.
- If outputLanguage is Arabic, include English medical terms in brackets.

INPUT:
- Age: ${userData.age || 'Not provided'}
- Description: "${userData.intakeText}"
- Medical history: ${userData.seenDoctorBefore
    ? `Has seen doctor. Findings: "${userData.doctorFindings || 'None'}"`
    : 'No prior doctor visit.'}
- Interview answers: ${JSON.stringify(userData.interviewAnswers || {})}

TASK 1 — INTERVIEW STEPS (only when interviewAnswers is empty):
Generate EXACTLY 8 follow-up questions in ${interviewLangName}.
Each must have exactly 4 suggestions in the same language.
8th question: ask if there is anything else she would like to add.

TASK 2 — CLINICAL OUTPUT (all in ${outputLangName}):

FRAME 1 — GUIDANCE:
- tips: 4 actionable, empathetic tips.
- potentialConditions: 2–3 medical possibilities with simple explanations.
- urgency: Green (Routine) / Yellow (See doctor soon) / Red (Emergency).

FRAME 2 — CLINICAL RECORD:
- narrative: Write exactly ONE sentence as a placeholder only (e.g. "I will describe my symptoms to my doctor."). The full narrative is generated by a separate call.
- summaryTable: Age (MUST BE "${userData.age || 'N/A'}"), Pain Scale, Location, Duration.
- doctorQuestions: 4 first-person questions to ask the doctor.

CRITICAL: narrative must be a 1-sentence placeholder. Nothing more.
`;
}

// ─── Handler ──────────────────────────────────────────────────────────────────
export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { userData, uiLanguage = 'EN', outputLanguage = 'EN' } = req.body;

    if (!userData?.intakeText) {
      return res.status(400).json({ error: 'intakeText is required' });
    }

    const ai = new GoogleGenAI({ apiKey });
    const prompt = buildPrompt(userData, uiLanguage, outputLanguage);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: ANALYSIS_SCHEMA,
        systemInstruction: `You are Clara, a professional medical communication assistant for women's health.
Age "${userData.age || 'N/A'}" is mandatory in the summary table.
Interview questions language: ${OUTPUT_LANG_NAMES[uiLanguage] || 'English'}.
Report language: ${OUTPUT_LANG_NAMES[outputLanguage] || 'English'}.
narrative: ONE placeholder sentence only — full narrative comes from a separate streaming call.`,
      },
    });

    if (!response.text) throw new Error('No response from AI');

    const result = JSON.parse(response.text);
    return res.status(200).json(result);

  } catch (err: any) {
    console.error('analyze error:', err);
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
