import { GoogleGenAI, Type } from "@google/genai";

const apiKey = process.env.GEMINI_API_KEY || "";

export type OutputLanguage = 'EN' | 'AR' | 'HI' | 'UR';

export interface InterviewStep {
  category: string;
  question: string;
  suggestions: string[];
}

export interface AnalysisResult {
  steps: InterviewStep[];
  guidance: {
    tips: string[];
    potentialConditions: { name: string; explanation: string }[];
    urgency: 'Green' | 'Yellow' | 'Red';
  };
  clinicalReport: {
    narrative: string;
    summaryTable: { label: string; value: string }[];
    doctorQuestions: string[];
  };
}

// ─── Schema ───────────────────────────────────────────────────────────────────

const ANALYSIS_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    steps: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          category: { type: Type.STRING },
          question: { type: Type.STRING },
          suggestions: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Exactly 4 quick reply options.",
          },
        },
        required: ["category", "question", "suggestions"],
      },
    },
    guidance: {
      type: Type.OBJECT,
      properties: {
        tips: { type: Type.ARRAY, items: { type: Type.STRING } },
        potentialConditions: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              explanation: { type: Type.STRING },
            },
            required: ["name", "explanation"],
          },
        },
        urgency: { type: Type.STRING, enum: ["Green", "Yellow", "Red"] },
      },
      required: ["tips", "potentialConditions", "urgency"],
    },
    clinicalReport: {
      type: Type.OBJECT,
      properties: {
        narrative: { type: Type.STRING },
        summaryTable: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              label: { type: Type.STRING },
              value: { type: Type.STRING },
            },
            required: ["label", "value"],
          },
        },
        doctorQuestions: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: ["narrative", "summaryTable", "doctorQuestions"],
    },
  },
  required: ["steps", "guidance", "clinicalReport"],
};

// ─── Language helpers ─────────────────────────────────────────────────────────

const OUTPUT_LANG_NAMES: Record<OutputLanguage, string> = {
  EN: 'English',
  AR: 'Arabic',
  HI: 'Hindi',
  UR: 'Urdu',
};

const FIRST_PERSON_STARTERS: Record<OutputLanguage, string> = {
  EN: "I feel / My pain started / I noticed",
  AR: "أشعر بـ / بدأ ألمي منذ / لاحظتُ أن",
  HI: "मुझे महसूस हो रहा है / मेरा दर्द शुरू हुआ / मैंने देखा",
  UR: "مجھے محسوس ہو رہا ہے / میرا درد شروع ہوا / میں نے محسوس کیا",
};

// ─── Shared prompt builder ────────────────────────────────────────────────────

function buildStructuredPrompt(
  userData: {
    intakeText: string;
    age?: string;
    seenDoctorBefore: boolean;
    doctorFindings?: string;
    interviewAnswers?: Record<string, string>;
  },
  uiLang: OutputLanguage,
  outputLang: OutputLanguage
): string {
  const outputLangName = OUTPUT_LANG_NAMES[outputLang];
  const interviewLangName = OUTPUT_LANG_NAMES[uiLang];

  return `
ROLE: Clara — Clinical Triage Expert.
MISSION: Transform patient symptoms into a respectful 2-frame clinical report.

LANGUAGE DIRECTIVE:
- Interview questions (steps): ${interviewLangName}.
- Final clinical report (guidance + clinicalReport): ${outputLangName}.
- Accept any dialect or informal language as input — understand it fully.
- If outputLanguage is Arabic, include English medical terms in brackets.

INPUT:
- Age: ${userData.age || 'Not provided'}
- Description: "${userData.intakeText}"
- Medical history: ${userData.seenDoctorBefore
    ? `Has seen doctor. Findings: "${userData.doctorFindings || 'None'}"`
    : 'No prior doctor visit.'}
- Interview answers: ${JSON.stringify(userData.interviewAnswers || {})}

TASK 1 — INTERVIEW STEPS (only when interviewAnswers is empty):
Generate EXACTLY 8 follow-up questions in ${interviewLangName}.
Each must have exactly 4 suggestions in the same language.
8th question: ask if there is anything else she would like to add.

TASK 2 — CLINICAL OUTPUT (all in ${outputLangName}):

FRAME 1 — GUIDANCE:
- tips: 4 actionable, empathetic tips.
- potentialConditions: 2–3 medical possibilities with simple explanations.
- urgency: Green (Routine) / Yellow (See doctor soon) / Red (Emergency).

FRAME 2 — CLINICAL RECORD:
- narrative: Write exactly ONE sentence as a placeholder only (e.g. "I will describe my symptoms to my doctor."). The full narrative is generated by a separate call.
- summaryTable: Age (MUST BE "${userData.age || 'N/A'}"), Pain Scale, Location, Duration.
- doctorQuestions: 4 first-person questions to ask the doctor.

CRITICAL: narrative must be a 1-sentence placeholder. Nothing more.
`;
}

// ─── CALL 1: Structured JSON ──────────────────────────────────────────────────

export async function analyzeStructured(
  userData: {
    intakeText: string;
    age?: string;
    seenDoctorBefore: boolean;
    doctorFindings?: string;
    interviewAnswers?: Record<string, string>;
  },
  uiLanguage: OutputLanguage = 'EN',
  outputLanguage: OutputLanguage = 'EN'
): Promise<AnalysisResult> {
  const ai = new GoogleGenAI({ apiKey });
  const prompt = buildStructuredPrompt(userData, uiLanguage, outputLanguage);

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: ANALYSIS_SCHEMA,
      systemInstruction: `You are Clara, a professional medical communication assistant for women's health.
Age "${userData.age || 'N/A'}" is mandatory in the summary table.
Interview questions language: ${OUTPUT_LANG_NAMES[uiLanguage]}.
Report language: ${OUTPUT_LANG_NAMES[outputLanguage]}.
narrative: ONE placeholder sentence only — full narrative comes from a separate streaming call.`,
    },
  });

  if (!response.text) throw new Error("No response from AI");
  return JSON.parse(response.text) as AnalysisResult;
}

// ─── CALL 2: Streaming narrative ──────────────────────────────────────────────

export async function streamNarrative(
  userData: {
    intakeText: string;
    age?: string;
    seenDoctorBefore: boolean;
    doctorFindings?: string;
    interviewAnswers?: Record<string, string>;
  },
  outputLanguage: OutputLanguage = 'EN',
  onChunk: (chunk: string) => void,
  onDone: (fullText: string) => void,
  onError: (err: unknown) => void
): Promise<void> {
  const ai = new GoogleGenAI({ apiKey });
  const langName = OUTPUT_LANG_NAMES[outputLanguage];
  const starters = FIRST_PERSON_STARTERS[outputLanguage];

  const prompt = `
You are Clara — a medical communication assistant writing a patient's personal clinical statement.

TASK: Write a detailed first-person clinical narrative (150–200 words) in ${langName}.

STRICT RULES:
- Write ONLY in ${langName}.
- Use FIRST PERSON exclusively. Use phrases like: ${starters}
- NEVER use "The patient", "She feels", "The user", or any third-person reference.
- Write as if YOU ARE the patient speaking directly to her doctor.
- Be descriptive, specific, and emotionally precise.
- Include: symptom onset, location, character of pain, aggravating/relieving factors, associated symptoms.
${outputLanguage === 'AR' ? '- Add English medical terms in brackets for clinical precision.' : ''}

PATIENT DATA:
- Age: ${userData.age || 'Not provided'}
- Initial description: "${userData.intakeText}"
- Medical history: ${userData.seenDoctorBefore
    ? `Has seen a doctor. Findings: "${userData.doctorFindings || 'None'}"`
    : 'No prior doctor visit.'}
- Detailed answers: ${JSON.stringify(userData.interviewAnswers || {})}

RESPOND WITH ONLY the narrative text. No labels, no JSON, no headers, no preamble.
`;

  try {
    const stream = await ai.models.generateContentStream({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    let fullText = '';
    for await (const chunk of stream) {
      const text = chunk.text ?? '';
      if (text) {
        fullText += text;
        onChunk(text);
      }
    }
    onDone(fullText);
  } catch (err) {
    onError(err);
  }
}

// ─── Legacy wrapper (kept for backward compatibility) ─────────────────────────

export async function analyzeExperience(
  userData: {
    intakeText: string;
    age?: string;
    seenDoctorBefore: boolean;
    doctorFindings?: string;
    interviewAnswers?: Record<string, string>;
  },
  uiLanguage: OutputLanguage = 'EN',
  outputLanguage: OutputLanguage = 'EN'
): Promise<AnalysisResult> {
  return analyzeStructured(userData, uiLanguage, outputLanguage);
}
