// types.ts
import { Language, Screen, UserData } from './lib/utils';

export interface AppState {
  language: Language;
  screen: Screen;
  userData: UserData;
}

export const INITIAL_STATE: AppState = {
  language: 'EN',
  screen: 'DISCLAIMER',
  userData: {
    agreedToTerms: false,
    intakeText: '',
    seenDoctorBefore: false,
  },
};

export const TRANSLATIONS = {
  EN: {
    disclaimer: {
      title: "Medical Symptom Documentation",
      text: "This tool helps you document symptoms for your doctor. It is not a diagnostic tool and does not replace professional medical advice. I am responsible for my health decisions.",
      button: "I Understand and Agree",
    },
    welcome: {
      title: "Your Medical Communication Assistant",
      subtitle: "Describe how you feel — in any language or dialect — and Clara turns it into a precise medical report for your doctor.",
      button: "Start Now",
      freeInputHint: "💬 Write in your dialect or everyday language. Clara understands.",
    },
    intake: {
      title: "How are you feeling?",
      placeholder: "Describe what you feel in your own words — dialect, everyday language, anything. Clara will handle the rest.",
      button: "Continue",
      voiceHint: "You can also use your voice",
      languageHint: "💬 No matter what language you write in, you'll choose your results language at the end.",
    },
    demographics: {
      title: "Could you tell me your age?",
      ageLabel: "My age is...",
      button: "Continue",
    },
    medical: {
      title: "My Medical History",
      doctorQuestion: "Have you seen a doctor before for this?",
      yes: "Yes, I have",
      no: "No, I haven't",
      findingsLabel: "Thank you. What did the doctor find?",
      findingsPlaceholder: "I was told that...",
      button: "Analyze My Symptoms",
    },
    analysis: {
      loading: "Processing clinical details...",
      streamingMessage: "Encrypting and analyzing your data in real time for your privacy...",
      title: "Follow-up Details",
      next: "Next",
      finish: "See Final Report",
      back: "Back",
      step: "Step",
      of: "of",
      precisionPlaceholder: "Type your answer here...",
      outputLangQuestion: "In which language would you like to receive your results?",
      outputLangHint: "Your report will be generated in this language, regardless of how you described your symptoms.",
    },
    results: {
      title: "Official Medical Symptom Report",
      doctorQuestions: "Physician's Diagnostic Checklist",
      doctorQuestionsLocked: "🔒 Sign in to unlock your Doctor Visit Checklist",
      copy: "Copy to Clipboard",
      downloadPDF: "Download Medical Report (PDF)",
      new: "Start New Assessment",
      copied: "Copied!",
      captureInstruction: "💡 Download the official PDF report to share with your doctor.",
      footer: "CLARA - CLINICAL ASSISTANT",
      narrativeStreaming: "Generating your personal clinical record...",
      autoDeleteLabel: "Delete this data automatically after downloading the report",
      autoDeleteConfirm: "✓ Your data has been cleared from this session.",
    },
    privacy: {
      badge: "End-to-End Encrypted",
      badgeShort: "E2E Encrypted",
      geminiNote: "Your data is used only for your medical analysis. It is never used to train public AI models.",
      streamingNote: "Your data is being encrypted and analyzed in real time...",
    },
    auth: {
      signIn: "Continue with Google",
      signOut: "Sign out",
      signingIn: "Signing in...",
      unlockPrompt: "Sign in to unlock your Doctor Visit Checklist",
    },
    toggle: "العربية",
  },
  AR: {
    disclaimer: {
      title: "توثيق الأعراض الطبية",
      text: "هذه الأداة تساعدكِ على توثيق أعراضكِ لعرضها على الطبيب. هي ليست أداة تشخيصية ولا تحل محل الاستشارة الطبية المتخصصة. أنا مسؤولة عن قراراتي الصحية.",
      button: "أوافق وأبدأ",
    },
    welcome: {
      title: "مساعدكِ للتواصل الطبي",
      subtitle: "صِفي ما تشعرين به بأي لغة أو لهجة — وكلارا ستحوّله إلى تقرير طبي دقيق لطبيبكِ.",
      button: "ابدئي الآن",
      freeInputHint: "💬 يمكنكِ الكتابة بالعامية أو الدارجة. كلارا تفهمكِ.",
    },
    intake: {
      title: "كيف تشعرين؟",
      placeholder: "صِفي ما تشعرين به بكلامكِ الخاص — بالعامية أو أي لغة تريحكِ. كلارا ستتولى الباقي.",
      button: "متابعة",
      voiceHint: "يمكنكِ أيضاً استخدام صوتكِ",
      languageHint: "💬 مهما كانت لغة وصفكِ، ستختارين لغة النتائج في النهاية.",
    },
    demographics: {
      title: "كم تبلغين من العمر؟",
      ageLabel: "عمري هو...",
      button: "متابعة",
    },
    medical: {
      title: "تاريخكِ الطبي",
      doctorQuestion: "هل سبق وأن استشرتِ طبيباً بشأن هذه الأعراض؟",
      yes: "نعم، فعلتُ",
      no: "لا، لم أفعل",
      findingsLabel: "شكراً. ما الذي وجده الطبيب؟",
      findingsPlaceholder: "قيل لي أن...",
      button: "تحليل الأعراض",
    },
    analysis: {
      loading: "جاري معالجة التفاصيل السريرية...",
      streamingMessage: "يتم الآن تحليل بياناتكِ وتشفيرها لحظياً لضمان خصوصيتكِ...",
      title: "متابعة التفاصيل",
      next: "التالي",
      finish: "رؤية التقرير النهائي",
      back: "رجوع",
      step: "الخطوة",
      of: "من",
      precisionPlaceholder: "اكتبي إجابتكِ هنا...",
      outputLangQuestion: "بأي لغة تريدين استلام النتائج؟",
      outputLangHint: "سيُولَّد تقريركِ بهذه اللغة بغض النظر عن كيفية وصفكِ للأعراض.",
    },
    results: {
      title: "التقرير الطبي الرسمي للأعراض",
      doctorQuestions: "قائمة مراجعة الطبيب التشخيصية",
      doctorQuestionsLocked: "🔒 سجّلي الدخول لفتح قائمة الأسئلة لمراجعة الطبيب",
      copy: "نسخ إلى الحافظة",
      downloadPDF: "تحميل التقرير الطبي (PDF)",
      new: "بدء تقييم جديد",
      copied: "تم النسخ!",
      captureInstruction: "💡 يمكنكِ الآن تحميل التقرير الطبي الرسمي بصيغة PDF.",
      footer: "CLARA - CLINICAL ASSISTANT",
      narrativeStreaming: "جاري توليد سجلكِ السريري الشخصي...",
      autoDeleteLabel: "حذف هذه البيانات تلقائياً بعد تحميل التقرير",
      autoDeleteConfirm: "✓ تم مسح بياناتكِ من هذه الجلسة.",
    },
    privacy: {
      badge: "مشفر من الطرف إلى الطرف",
      badgeShort: "E2E مشفر",
      geminiNote: "بياناتكِ تُستخدم فقط لتحليل حالتكِ الطبية. لا تُستخدم أبداً لتدريب نماذج الذكاء الاصطناعي العامة.",
      streamingNote: "يتم الآن تحليل بياناتكِ وتشفيرها لحظياً لضمان خصوصيتكِ...",
    },
    auth: {
      signIn: "الدخول بـ Google",
      signOut: "خروج",
      signingIn: "جاري تسجيل الدخول...",
      unlockPrompt: "سجّلي الدخول للحصول على قائمة الأسئلة لمراجعة الطبيب",
    },
    toggle: "English",
  },
  HI: {
    disclaimer: {
      title: "चिकित्सा लक्षण दस्तावेज़ीकरण",
      text: "यह टूल आपके डॉक्टर के लिए लक्षणों को दर्ज करने में मदद करता है। यह निदान उपकरण नहीं है। मैं अपने स्वास्थ्य निर्णयों की ज़िम्मेदार हूँ।",
      button: "मैं समझती हूँ और सहमत हूँ",
    },
    welcome: {
      title: "आपकी मेडिकल कम्युनिकेशन असिस्टेंट",
      subtitle: "किसी भी भाषा या बोली में बताएं कि आप कैसा महसूस कर रही हैं — Clara इसे डॉक्टर के लिए रिपोर्ट में बदल देगी।",
      button: "अभी शुरू करें",
      freeInputHint: "💬 अपनी बोली में लिखें। Clara समझेगी।",
    },
    intake: {
      title: "आप कैसा महसूस कर रही हैं?",
      placeholder: "अपने शब्दों में बताएं — बोली, रोज़मर्रा की भाषा, कुछ भी। Clara बाकी सब संभाल लेगी।",
      button: "जारी रखें",
      voiceHint: "आप आवाज़ भी उपयोग कर सकती हैं",
      languageHint: "💬 चाहे किसी भी भाषा में लिखें, अंत में आप परिणाम की भाषा चुनेंगी।",
    },
    demographics: {
      title: "कृपया अपनी उम्र बताएं?",
      ageLabel: "मेरी उम्र है...",
      button: "जारी रखें",
    },
    medical: {
      title: "मेरा मेडिकल इतिहास",
      doctorQuestion: "क्या आपने पहले इसके लिए डॉक्टर से मिली हैं?",
      yes: "हाँ, मिली हूँ",
      no: "नहीं, नहीं मिली",
      findingsLabel: "शुक्रिया। डॉक्टर ने क्या बताया?",
      findingsPlaceholder: "मुझे बताया गया कि...",
      button: "लक्षणों का विश्लेषण करें",
    },
    analysis: {
      loading: "नैदानिक विवरण प्रोसेस हो रहे हैं...",
      streamingMessage: "आपकी गोपनीयता के लिए आपके डेटा को रीयल-टाइम में एन्क्रिप्ट किया जा रहा है...",
      title: "अतिरिक्त विवरण",
      next: "अगला",
      finish: "अंतिम रिपोर्ट देखें",
      back: "वापस",
      step: "चरण",
      of: "का",
      precisionPlaceholder: "यहाँ उत्तर लिखें...",
      outputLangQuestion: "आप किस भाषा में परिणाम चाहती हैं?",
      outputLangHint: "आपकी रिपोर्ट इसी भाषा में बनाई जाएगी।",
    },
    results: {
      title: "आधिकारिक मेडिकल रिपोर्ट",
      doctorQuestions: "डॉक्टर के लिए प्रश्न सूची",
      doctorQuestionsLocked: "🔒 डॉक्टर चेकलिस्ट के लिए साइन इन करें",
      copy: "क्लिपबोर्ड पर कॉपी करें",
      downloadPDF: "PDF रिपोर्ट डाउनलोड करें",
      new: "नया मूल्यांकन शुरू करें",
      copied: "कॉपी हो गई!",
      captureInstruction: "💡 PDF रिपोर्ट डाउनलोड करें और डॉक्टर को दिखाएं।",
      footer: "CLARA - CLINICAL ASSISTANT",
      narrativeStreaming: "आपका व्यक्तिगत नैदानिक रिकॉर्ड बन रहा है...",
      autoDeleteLabel: "रिपोर्ट डाउनलोड के बाद यह डेटा स्वचालित रूप से हटा दें",
      autoDeleteConfirm: "✓ आपका डेटा इस सेशन से हटा दिया गया।",
    },
    privacy: {
      badge: "एंड-टू-एंड एन्क्रिप्टेड",
      badgeShort: "E2E एन्क्रिप्टेड",
      geminiNote: "आपका डेटा केवल आपके चिकित्सा विश्लेषण के लिए उपयोग किया जाता है। इसे कभी AI प्रशिक्षण के लिए उपयोग नहीं किया जाता।",
      streamingNote: "आपकी गोपनीयता सुनिश्चित करने के लिए आपके डेटा को रीयल-टाइम में एन्क्रिप्ट किया जा रहा है...",
    },
    auth: {
      signIn: "Google से जारी रखें",
      signOut: "साइन आउट",
      signingIn: "साइन इन हो रही हैं...",
      unlockPrompt: "डॉक्टर चेकलिस्ट के लिए साइन इन करें",
    },
    toggle: "اردو",
  },
  UR: {
    disclaimer: {
      title: "طبی علامات کی دستاویز",
      text: "یہ ٹول آپ کے ڈاکٹر کے لیے علامات درج کرنے میں مدد کرتا ہے۔ یہ تشخیصی آلہ نہیں ہے۔ میں اپنے صحت کے فیصلوں کی ذمہ دار ہوں۔",
      button: "میں سمجھتی ہوں اور رضامند ہوں",
    },
    welcome: {
      title: "آپ کی طبی رابطہ معاون",
      subtitle: "کسی بھی زبان یا بولی میں بتائیں — Clara اسے ڈاکٹر کے لیے رپورٹ میں بدل دے گی۔",
      button: "ابھی شروع کریں",
      freeInputHint: "💬 اپنی بولی میں لکھیں۔ Clara سمجھے گی۔",
    },
    intake: {
      title: "آپ کیسا محسوس کر رہی ہیں؟",
      placeholder: "اپنے الفاظ میں بیان کریں — بولی، روزمرہ کی زبان، کچھ بھی۔ Clara باقی سنبھال لے گی۔",
      button: "جاری رکھیں",
      voiceHint: "آپ آواز بھی استعمال کر سکتی ہیں",
      languageHint: "💬 چاہے کسی بھی زبان میں لکھیں، آخر میں نتائج کی زبان آپ خود منتخب کریں گی۔",
    },
    demographics: {
      title: "براہ کرم اپنی عمر بتائیں؟",
      ageLabel: "میری عمر ہے...",
      button: "جاری رکھیں",
    },
    medical: {
      title: "میری طبی تاریخ",
      doctorQuestion: "کیا آپ نے پہلے اس کے لیے ڈاکٹر سے ملی ہیں؟",
      yes: "ہاں، ملی ہوں",
      no: "نہیں، نہیں ملی",
      findingsLabel: "شکریہ۔ ڈاکٹر نے کیا بتایا؟",
      findingsPlaceholder: "مجھے بتایا گیا کہ...",
      button: "علامات کا تجزیہ کریں",
    },
    analysis: {
      loading: "طبی تفصیلات پروسیس ہو رہی ہیں...",
      streamingMessage: "آپ کی رازداری کے لیے آپ کا ڈیٹا ریئل ٹائم میں انکرپٹ ہو رہا ہے...",
      title: "اضافی تفصیلات",
      next: "اگلا",
      finish: "آخری رپورٹ دیکھیں",
      back: "واپس",
      step: "مرحلہ",
      of: "کا",
      precisionPlaceholder: "یہاں جواب لکھیں...",
      outputLangQuestion: "آپ کس زبان میں نتائج چاہتی ہیں؟",
      outputLangHint: "آپ کی رپورٹ اسی زبان میں تیار کی جائے گی۔",
    },
    results: {
      title: "سرکاری طبی رپورٹ",
      doctorQuestions: "ڈاکٹر کے لیے سوالات کی فہرست",
      doctorQuestionsLocked: "🔒 ڈاکٹر چیک لسٹ کے لیے سائن ان کریں",
      copy: "کلپ بورڈ پر کاپی کریں",
      downloadPDF: "PDF رپورٹ ڈاؤنلوڈ کریں",
      new: "نئی جانچ شروع کریں",
      copied: "کاپی ہو گئی!",
      captureInstruction: "💡 PDF رپورٹ ڈاؤنلوڈ کریں اور ڈاکٹر کو دکھائیں۔",
      footer: "CLARA - CLINICAL ASSISTANT",
      narrativeStreaming: "آپ کا ذاتی طبی ریکارڈ بن رہا ہے...",
      autoDeleteLabel: "رپورٹ ڈاؤنلوڈ کے بعد یہ ڈیٹا خود بخود حذف کریں",
      autoDeleteConfirm: "✓ آپ کا ڈیٹا اس سیشن سے حذف کر دیا گیا۔",
    },
    privacy: {
      badge: "اینڈ ٹو اینڈ انکرپٹڈ",
      badgeShort: "E2E انکرپٹڈ",
      geminiNote: "آپ کا ڈیٹا صرف آپ کے طبی تجزیے کے لیے استعمال ہوتا ہے۔ اسے کبھی AI تربیت کے لیے استعمال نہیں کیا جاتا۔",
      streamingNote: "آپ کی رازداری کے لیے آپ کا ڈیٹا ریئل ٹائم میں انکرپٹ ہو رہا ہے...",
    },
    auth: {
      signIn: "Google سے جاری رکھیں",
      signOut: "سائن آؤٹ",
      signingIn: "سائن ان ہو رہی ہیں...",
      unlockPrompt: "ڈاکٹر چیک لسٹ کے لیے سائن ان کریں",
    },
    toggle: "हिंदी",
  },
};
