import { Language, Screen, UserData } from './lib/utils';

export interface AppState {
  language: Language;
  screen: Screen;
  userData: UserData;
}

export const INITIAL_STATE: AppState = {
  language: 'EN',
  screen: 'DISCLAIMER',
  userData: {
    agreedToTerms: false,
    intakeText: '',
    seenDoctorBefore: false,
  },
};

export const TRANSLATIONS = {
  EN: {
    disclaimer: {
      title: "Medical Symptom Documentation",
      text: "This tool helps you document symptoms for your doctor. It is not a diagnostic tool and does not replace professional medical advice. I am responsible for my health decisions.",
      button: "I Understand and Agree",
    },
    welcome: {
      title: "Your Medical Communication Assistant",
      subtitle: "Describe how you feel — in any language, any dialect — and Clara will translate it into a precise medical report for your doctor.",
      button: "Start Now",
      freeInputHint: "💬 You can write in your dialect or everyday language. Clara understands.",
    },
    intake: {
      title: "How are you feeling?",
      placeholder: "Describe what you feel in your own words — dialect, everyday language, anything. Clara will handle the rest.",
      button: "Continue to Detailed Analysis",
      voiceHint: "You can also use your voice",
    },
    demographics: {
      title: "Could you tell me your age, please?",
      ageLabel: "My age is...",
      button: "Continue",
    },
    medical: {
      title: "My Medical History",
      doctorQuestion: "Have you seen a doctor before for this?",
      yes: "Yes, I have",
      no: "No, I haven't",
      findingsLabel: "Thank you. What did the doctor find?",
      findingsPlaceholder: "I was told that...",
      button: "Analyze My Symptoms",
    },
    analysis: {
      loading: "Processing clinical details...",
      title: "Follow-up Details",
      next: "Next",
      finish: "See Final Report",
      back: "Back",
      step: "Step",
      of: "of",
      precisionPlaceholder: "Type your answer here...",
    },
    outputLanguage: {
      title: "Choose your results language",
      subtitle: "Your report will be generated in the language you select.",
    },
    results: {
      title: "Official Medical Symptom Report",
      doctorQuestions: "Physician's Diagnostic Checklist",
      doctorQuestionsLocked: "🔒 Sign in to unlock your Doctor Visit Checklist",
      copy: "Copy to Clipboard",
      downloadPDF: "Download Medical Report (PDF)",
      new: "Start New Assessment",
      copied: "Copied!",
      captureInstruction: "💡 You can now download the official PDF report to share with your doctor.",
      footer: "CLARA - CLINICAL ASSISTANT",
      signInPrompt: "Sign in to unlock your personalized doctor checklist",
    },
    auth: {
      signIn: "Continue with Google",
      signOut: "Sign out",
      signingIn: "Signing in...",
      unlockPrompt: "Sign in to unlock your Doctor Visit Checklist",
    },
    toggle: "العربية",
  },
  AR: {
    disclaimer: {
      title: "توثيق الأعراض الطبية",
      text: "هذه الأداة تساعدكِ على توثيق أعراضكِ لعرضها على الطبيب. هي ليست أداة تشخيصية ولا تحل محل الاستشارة الطبية المتخصصة. أنا مسؤولة عن قراراتي الصحية.",
      button: "أوافق وأبدأ",
    },
    welcome: {
      title: "مساعدكِ للتواصل الطبي",
      subtitle: "صِفي ما تشعرين به بأي لغة أو لهجة — وكلارا ستحوّله إلى تقرير طبي دقيق لطبيبكِ.",
      button: "ابدئي الآن",
      freeInputHint: "💬 يمكنكِ الكتابة بالعامية أو باللهجة التي تريحكِ. كلارا تفهمكِ.",
    },
    intake: {
      title: "كيف تشعرين؟",
      placeholder: "صِفي ما تشعرين به بكلامكِ الخاص — بالعامية أو الدارجة أو أي لغة تريحكِ. كلارا ستتولى الباقي.",
      button: "المتابعة للتحليل التفصيلي",
      voiceHint: "يمكنكِ أيضاً استخدام صوتكِ",
    },
    demographics: {
      title: "كم تبلغين من العمر؟",
      ageLabel: "عمري هو...",
      button: "متابعة",
    },
    medical: {
      title: "تاريخكِ الطبي",
      doctorQuestion: "هل سبق وأن استشرتِ طبيباً بشأن هذه الأعراض؟",
      yes: "نعم، فعلتُ",
      no: "لا، لم أفعل",
      findingsLabel: "شكراً. ما الذي وجده الطبيب؟",
      findingsPlaceholder: "قيل لي أن...",
      button: "تحليل الأعراض",
    },
    analysis: {
      loading: "جاري معالجة التفاصيل السريرية...",
      title: "متابعة التفاصيل",
      next: "التالي",
      finish: "رؤية التقرير النهائي",
      back: "رجوع",
      step: "الخطوة",
      of: "من",
      precisionPlaceholder: "اكتبي إجابتكِ هنا...",
    },
    outputLanguage: {
      title: "اختاري لغة النتائج",
      subtitle: "سيتم توليد تقريركِ باللغة التي تختارينها.",
    },
    results: {
      title: "التقرير الطبي الرسمي للأعراض",
      doctorQuestions: "قائمة مراجعة الطبيب التشخيصية",
      doctorQuestionsLocked: "🔒 سجّلي الدخول لفتح قائمة الأسئلة لمراجعة الطبيب",
      copy: "نسخ إلى الحافظة",
      downloadPDF: "تحميل التقرير الطبي (PDF)",
      new: "بدء تقييم جديد",
      copied: "تم النسخ!",
      captureInstruction: "💡 يمكنكِ الآن تحميل التقرير الطبي الرسمي بصيغة PDF لمشاركته مع طبيبكِ.",
      footer: "CLARA - CLINICAL ASSISTANT",
      signInPrompt: "سجّلي الدخول لفتح قائمة أسئلة الطبيب المخصصة",
    },
    auth: {
      signIn: "الدخول بـ Google",
      signOut: "خروج",
      signingIn: "جاري تسجيل الدخول...",
      unlockPrompt: "سجّلي الدخول للحصول على قائمة الأسئلة لمراجعة الطبيب",
    },
    toggle: "English",
  },
  HI: {
    disclaimer: {
      title: "चिकित्सा लक्षण दस्तावेज़ीकरण",
      text: "यह टूल आपके डॉक्टर के लिए आपके लक्षणों को दर्ज करने में मदद करता है। यह कोई निदान उपकरण नहीं है और यह पेशेवर चिकित्सा सलाह की जगह नहीं ले सकता। मैं अपने स्वास्थ्य निर्णयों के लिए जिम्मेदार हूँ।",
      button: "मैं समझती हूँ और सहमत हूँ",
    },
    welcome: {
      title: "आपकी मेडिकल कम्युनिकेशन असिस्टेंट",
      subtitle: "किसी भी भाषा या बोली में बताएं कि आप कैसा महसूस कर रही हैं — Clara इसे आपके डॉक्टर के लिए एक सटीक मेडिकल रिपोर्ट में बदल देगी।",
      button: "अभी शुरू करें",
      freeInputHint: "💬 आप अपनी बोली या रोज़मर्रा की भाषा में लिख सकती हैं। Clara समझेगी।",
    },
    intake: {
      title: "आप कैसा महसूस कर रही हैं?",
      placeholder: "अपने शब्दों में बताएं — बोली, रोज़मर्रा की भाषा, कुछ भी। Clara बाकी सब संभाल लेगी।",
      button: "विस्तृत विश्लेषण जारी रखें",
      voiceHint: "आप अपनी आवाज़ भी उपयोग कर सकती हैं",
    },
    demographics: {
      title: "कृपया अपनी उम्र बताएं?",
      ageLabel: "मेरी उम्र है...",
      button: "जारी रखें",
    },
    medical: {
      title: "मेरा मेडिकल इतिहास",
      doctorQuestion: "क्या आपने पहले इसके लिए डॉक्टर से मिली हैं?",
      yes: "हाँ, मिली हूँ",
      no: "नहीं, नहीं मिली",
      findingsLabel: "शुक्रिया। डॉक्टर ने क्या बताया था?",
      findingsPlaceholder: "मुझे बताया गया कि...",
      button: "लक्षणों का विश्लेषण करें",
    },
    analysis: {
      loading: "नैदानिक विवरण प्रोसेस हो रहे हैं...",
      title: "अतिरिक्त विवरण",
      next: "अगला",
      finish: "अंतिम रिपोर्ट देखें",
      back: "वापस",
      step: "चरण",
      of: "का",
      precisionPlaceholder: "यहाँ अपना उत्तर लिखें...",
    },
    outputLanguage: {
      title: "परिणाम की भाषा चुनें",
      subtitle: "आपकी रिपोर्ट चुनी गई भाषा में बनाई जाएगी।",
    },
    results: {
      title: "आधिकारिक मेडिकल लक्षण रिपोर्ट",
      doctorQuestions: "चिकित्सक की जाँच सूची",
      doctorQuestionsLocked: "🔒 डॉक्टर विज़िट चेकलिस्ट अनलॉक करने के लिए साइन इन करें",
      copy: "क्लिपबोर्ड पर कॉपी करें",
      downloadPDF: "मेडिकल रिपोर्ट डाउनलोड करें (PDF)",
      new: "नया मूल्यांकन शुरू करें",
      copied: "कॉपी हो गई!",
      captureInstruction: "💡 अब आप अपने डॉक्टर के साथ शेयर करने के लिए आधिकारिक PDF रिपोर्ट डाउनलोड कर सकती हैं।",
      footer: "CLARA - CLINICAL ASSISTANT",
      signInPrompt: "अपनी व्यक्तिगत डॉक्टर चेकलिस्ट अनलॉक करने के लिए साइन इन करें",
    },
    auth: {
      signIn: "Google से जारी रखें",
      signOut: "साइन आउट",
      signingIn: "साइन इन हो रही हैं...",
      unlockPrompt: "डॉक्टर विज़िट प्रश्न सूची के लिए साइन इन करें",
    },
    toggle: "اردو",
  },
  UR: {
    disclaimer: {
      title: "طبی علامات کی دستاویز",
      text: "یہ ٹول آپ کے ڈاکٹر کے لیے آپ کی علامات کو درج کرنے میں مدد کرتا ہے۔ یہ تشخیصی آلہ نہیں ہے اور پیشہ ورانہ طبی مشورے کی جگہ نہیں لے سکتا۔ میں اپنے صحت کے فیصلوں کی ذمہ دار ہوں۔",
      button: "میں سمجھتی ہوں اور رضامند ہوں",
    },
    welcome: {
      title: "آپ کی طبی رابطہ معاون",
      subtitle: "کسی بھی زبان یا بولی میں بتائیں کہ آپ کیسا محسوس کر رہی ہیں — Clara اسے آپ کے ڈاکٹر کے لیے ایک درست طبی رپورٹ میں تبدیل کر دے گی۔",
      button: "ابھی شروع کریں",
      freeInputHint: "💬 آپ اپنی بولی یا روزمرہ کی زبان میں لکھ سکتی ہیں۔ Clara سمجھے گی۔",
    },
    intake: {
      title: "آپ کیسا محسوس کر رہی ہیں؟",
      placeholder: "اپنے الفاظ میں بیان کریں — بولی، روزمرہ کی زبان، کچھ بھی۔ Clara باقی سب سنبھال لے گی۔",
      button: "تفصیلی تجزیہ جاری رکھیں",
      voiceHint: "آپ اپنی آواز بھی استعمال کر سکتی ہیں",
    },
    demographics: {
      title: "براہ کرم اپنی عمر بتائیں؟",
      ageLabel: "میری عمر ہے...",
      button: "جاری رکھیں",
    },
    medical: {
      title: "میری طبی تاریخ",
      doctorQuestion: "کیا آپ نے پہلے اس کے لیے ڈاکٹر سے ملی ہیں؟",
      yes: "ہاں، ملی ہوں",
      no: "نہیں، نہیں ملی",
      findingsLabel: "شکریہ۔ ڈاکٹر نے کیا بتایا تھا؟",
      findingsPlaceholder: "مجھے بتایا گیا کہ...",
      button: "علامات کا تجزیہ کریں",
    },
    analysis: {
      loading: "طبی تفصیلات پروسیس ہو رہی ہیں...",
      title: "اضافی تفصیلات",
      next: "اگلا",
      finish: "آخری رپورٹ دیکھیں",
      back: "واپس",
      step: "مرحلہ",
      of: "کا",
      precisionPlaceholder: "یہاں اپنا جواب لکھیں...",
    },
    outputLanguage: {
      title: "نتائج کی زبان منتخب کریں",
      subtitle: "آپ کی رپورٹ منتخب زبان میں تیار کی جائے گی۔",
    },
    results: {
      title: "سرکاری طبی علامات رپورٹ",
      doctorQuestions: "معالج کی تشخیصی چیک لسٹ",
      doctorQuestionsLocked: "🔒 ڈاکٹر وزٹ چیک لسٹ کھولنے کے لیے سائن ان کریں",
      copy: "کلپ بورڈ پر کاپی کریں",
      downloadPDF: "طبی رپورٹ ڈاؤنلوڈ کریں (PDF)",
      new: "نئی جانچ شروع کریں",
      copied: "کاپی ہو گئی!",
      captureInstruction: "💡 اب آپ اپنے ڈاکٹر کے ساتھ شیئر کرنے کے لیے سرکاری PDF رپورٹ ڈاؤنلوڈ کر سکتی ہیں۔",
      footer: "CLARA - CLINICAL ASSISTANT",
      signInPrompt: "اپنی ذاتی ڈاکٹر چیک لسٹ کھولنے کے لیے سائن ان کریں",
    },
    auth: {
      signIn: "Google سے جاری رکھیں",
      signOut: "سائن آؤٹ",
      signingIn: "سائن ان ہو رہی ہیں...",
      unlockPrompt: "ڈاکٹر وزٹ سوالات کی فہرست کے لیے سائن ان کریں",
    },
    toggle: "हिंदी",
  },
};
